use_frameworks!

platform :ios, '10.0'

target 'myRepository_Example' do
  pod 'myRepository', :path => '../'

  target 'myRepository_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
